export { CryptFlare } from './client';
export { VERSION as version } from './version';

export {
  APIError,
  AuthenticationError,
  BadRequestError,
  ConfigurationError,
  ConflictError,
  ConnectionError,
  CryptFlareError,
  ERRORS,
  InternalServerError,
  NotFoundError,
  PermissionDeniedError,
  RateLimitError,
  TimeoutError,
  UnknownAPIError,
  UnprocessableEntityError,
  mapResponseToError,
} from './core/errors';
export type { ErrorCode, ErrorDetail } from './core/errors';

export { CursorPage } from './core/pagination';
export type { PageEnvelope } from './core/pagination';
export { PagePromise } from './core/page-promise';

export { verifyWebhook, WebhookVerificationError } from './core/webhooks';
export type { VerifyOptions as VerifyWebhookOptions } from './core/webhooks';
export { WEBHOOK_EVENT_TYPES, isKnownEventType } from './types/webhooks';
export type { WebhookEvent, WebhookEventPayloads, WebhookEventType } from './types/webhooks';

export { LocalKeyring, isEnvelope, seal, unseal } from './core/crypto';
export type { Envelope, Keyring } from './core/crypto';

export { EventStream } from './core/event-stream';
export type { EventStreamOptions } from './core/event-stream';
export { parseSSE } from './core/streaming';
export type { ServerEvent } from './core/streaming';

export type {
  ClientHooks,
  ClientOptions,
  HttpMethod,
  RequestEvent,
  RequestOptions,
  ResponseEvent,
  RetryEvent,
  RetryOptions,
} from './types/options';

export type {
  AccessGrant,
  AccessRequest,
  AuthMeResponse,
  AuthWhoamiResponse,
  BatchOperationResponse,
  ChangeMemberRoleInput,
  CreateEnvironmentInput,
  CreateOrgInput,
  CreatePodInput,
  CreateServiceTokenInput,
  CreateTokenInput,
  CreateWorkspaceInput,
  CreatedServiceToken,
  CreatedToken,
  EnvironmentItem,
  FeaturesResponse,
  GenerateReportInput,
  GenerateReportResponse,
  GlobalPolicy,
  InviteMemberInput,
  LoginInput,
  LoginResponse,
  MemberItem,
  MemberRecord,
  OrgDetail,
  OrgItem,
  OrgTeamPolicy,
  PoliciesTeamPolicy,
  PodAncestor,
  PodItem,
  PolicyTemplate,
  ReportStatusResponse,
  ResolvePathResponse,
  ResolvedPodPayload,
  ResolvedSecretPayload,
  Scope,
  SecretCreateInput,
  SecretCreateResponse,
  SecretListItem,
  SecretListResponse,
  SecretMoveInput,
  SecretMoveResponse,
  SecretRevealResponse,
  SecretRollbackInput,
  SecretRollbackResponse,
  SecretRotateInput,
  SecretRotateResponse,
  SecretSettings,
  SecretVersion,
  SecretVersionsResponse,
  ServiceTokenItem,
  SsoToggleInput,
  TagInput,
  Team,
  TeamListItem,
  TeamMember,
  TeamMemberRow,
  TeamPolicy,
  ToggleFeatureInput,
  ToggleFeatureResponse,
  TokenItem,
  TotpCodeInput,
  TotpSetupResponse,
  TotpVerifySetupResponse,
  UpdateOrgInput,
  UpdatePodInput,
  UpdateRolePermissionInput,
  UpdateSecretSettingsInput,
  UpdateServiceTokenInput,
  VerifyOtpInput,
  VerifyOtpResponse,
  VerifyTotpInput,
  WhoAmI,
  WorkspaceItem,
} from './types';

export {
  APIResource,
  Analytics,
  Audit,
  Auth,
  Billing,
  Cli,
  Compliance,
  Dashboard,
  DataResidency,
  Deployments,
  DynamicSecrets,
  Encryption,
  Environments,
  EventSubscriptions,
  Feedback,
  Integrations,
  Invitations,
  IpAllowlist,
  Me,
  Notifications,
  Onboarding,
  Organisations,
  Pods,
  Policies,
  RolePermissions,
  RotationPolicies,
  Search,
  Secrets,
  ServiceTokens,
  Sso,
  Status,
  Support,
  SyncConnections,
  Tags,
  Teams,
  Tokens,
  Transfers,
  Usage,
  Waitlist,
  WellKnown,
  Workspaces,
} from './resources';
